---
- name: setup_Firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 7777/udp
    - 7778/udp
    - 7779/udp
    - 7780/udp
    - 27015/udp
    - 27016/udp
    - 27017/udp
    - 27018/udp
    - 32330/tcp
  notify: firewalld

- name: mod_sysctl.conf
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: fs.file-max
    value: 100000
    state: present

- name: mod_limits.conf
  pam_limits:
    domain: "*"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 1000000
  with_items:
    - soft
    - hard

- name: install_Ark
  command: "{{ steam_home }}/steamcmd.sh +login anonymous +app_update {{ steam_ark }} +quit"
  become: yes
  become_user: "{{ steam_user }}"
  register: install
  changed_when: install.stdout.find("Success! App '376030' fully installed.") != -1

- name: systemdTemplate
  template:
    src:  "ark-dedicated.service.j2"
    dest: "/etc/systemd/system/ark-{{ item.key }}.service"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ ark_map }}"
  notify: restartArk

- name: enable/startService
  systemd:
    daemon_reload: yes
    state: started
    name: "ark-{{ item.key }}.service"
    enabled: yes
  with_dict: "{{ ark_map }}"

- name: gameiniTemplate
  template:
    src: "Game.ini.j2"
    dest: "{{ ark_config_dir }}/Game.ini"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    mode: 0400
  notify: restartArk

- name: gameusersettingsiniTemplate
  template:
    src: "GameUserSettings.ini.j2"
    dest: "{{ ark_config_dir }}/GameUserSettings.ini"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    mode: 0400
  notify: restartArk
