---
- name: install_preReqs
  yum:
    name:
      - screen
    state: latest

- name: create_scripts_folder
  file:
    path: "{{ scripts_home }}"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    state: directory

- name: setup_Firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 7777/udp
    - 27015/udp
    - 32330/tcp
  register: firewall

- name: restart_Firewall
  systemd:
    name: firewalld
    state: restarted
  when: firewall.changed

- name: mod_sysctl.conf
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: fs.file-max
    value: 100000
    state: present

- name: mod_limits.conf
  pam_limits:
    domain: "*"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 1000000
  with_items:
    - soft
    - hard

- name: templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ scripts_home }}/{{ item }}"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    mode: 0700
  with_items:
    - startArk.sh
    - stopArk.sh
    - updateArk.sh

- name: install_Ark
  command: "{{ scripts_home }}/updateArk.sh"
  become: yes
  become_user: "{{ steam_user }}"
  register: install
  changed_when: install.stdout.find("Success! App '376030' fully installed.") != -1

- name: systemdTemplate
  template:
    src:  "ark-dedicated.service.j2"
    dest: /etc/systemd/system/ark-dedicated.service
    owner: root
    group: root
    mode: 0644

- name: gameiniTemplate
  template:
    src: "Game.ini.j2"
    dest: "{{ ark_config_dir }}/Game.ini"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    mode: 0600

- name: gameusersettingsiniTemplate
  template:
    src: "Game.ini.j2"
    dest: "{{ ark_config_dir }}/GameUserSettings.ini"
    owner: "{{ steam_user }}"
    group: "{{ steam_user }}"
    mode: 0600

    - name: enable/startService
  systemd:
    daemon_reload: yes
    state: started
    name: ark-dedicated.service
    enabled: yes
