---
- name: resolv.conf_Template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: restart_Network
  service:
    name: network
    state: restarted