---
# Created by: Paul Camarata

- name: add_jenkins_repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644

- name: add_repo_key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install_Jenkins
  yum:
    name:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - jenkins
    state: latest

- name: enable_Jenkins_Daemon
  systemd:
    state: started
    name: jenkins
    enabled: yes

- name: enable_firewall
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  register: firewall

- name: restart_Firewall
  systemd:
    name: firewalld
    state: restarted
  when: firewall.changed