---
userId: prometheus
groupId: "{{ userId }}"
version: 2.5.0
serviceName: "prometheus"
exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.conf --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"
