- name: Restart the Prometheus service
  systemd:
    name: "{{ serviceName }}"
    state: restarted
    daemon_reload: yes
  listen: systemd_reload

- name: Restart the Firewalld service
  systemd:
    name: "firewalld"
    state: restarted
    daemon_reload: yes
  listen: firewalld